Add support for GeoIP2 anonymous database
logstash-plugins/logstash-filter-geoip pull request #141
Opened 2018-07-08 21:49 UTC by mdevreugd

Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

2018-10-25 08:49 UTC, zeysh commented on src/main/java/org/logstash/filters/GeoIPFilter.java
> +            geoData.put(Fields.ANONYMOUS_IS_ANONYMOUS.fieldName(), is_anonoymous);
:+1:

2018-10-25 08:49 UTC, zeysh commented on src/main/java/org/logstash/filters/GeoIPFilter.java
> +            geoData.put(Fields.ANONYMOUS_IS_ANONYMOUS.fieldName(), is_anonoymous);
:+1:

2018-12-20 21:17 UTC, 9uill4ume commented
@mdevreugd : how can we do so that our changes are validated and merged ? I can spend time on it, if you want.

2021-03-09 02:21 UTC, psdjc commented
+1

2024-12-23 08:38 UTC, Jokawild88 requested changes

2024-12-23 08:38 UTC, Jokawild88 commented on vendor.json
>          "url": "http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz",
Que

2024-12-23 08:50 UTC, edmocosta commented
Closing this PR as this feature was added through https://github.com/logstash-plugins/logstash-filter-geoip/pull/223.

2024-12-23 08:50 UTC, closed without merging